FuelEst/fuelest/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from . import views
from fuelest.views import HomePageView, ProfileView, QuoteListView, SuccessView

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='fuelest/login.html')),
    path('index/', HomePageView.as_view(), name="login"),
    path('profile/', ProfileView.as_view(), name="profile"),
    path('profile/edit/', views.profile_model, name="editprof"),
    path('register/', views.register_model, name="register"),
    path('quotes/generate/', views.quote_model, name="quotegen"),
    path('quotes/success/', SuccessView.as_view(), name="quotesuccess"),
    path('quotes/history/', QuoteListView.as_view(), name="quotehist"),
]

FuelEst/sdsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('fuelest.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

FuelEst/fuelest/models.py
from django.conf import settings
from django.db import models

STATES = [
    ('AL', 'Alabama'),
    ('AK', 'Alaska'),
    ('AZ', 'Arizona'),
    ('AR', 'Arkansas'),
    ('CA', 'California'),
    ('CO', 'Colorado'),
    ('CT', 'Connecticut'),
    ('DE', 'Delaware'),
    ('FL', 'Florida'),
    ('GA', 'Georgia'),
    ('HI', 'Hawaii'),
    ('ID', 'Idaho'),
    ('IL', 'Illinois'),
    ('IN', 'Indiana'),
    ('IA', 'Iowa'),
    ('KS', 'Kansas'),
    ('KY', 'Kentucky'),
    ('LA', 'Louisiana'),
    ('ME', 'Maine'),
    ('MD', 'Maryland'),
    ('MA', 'Massachusetts'),
    ('MI', 'Michigan'),
    ('MN', 'Minnesota'),
    ('MS', 'Mississippi'),
    ('MO', 'Missouri'),
    ('MT', 'Montana'),
    ('NE', 'Nebraska'),
    ('NV', 'Nevada'),
    ('NH', 'New Hampshire'),
    ('NJ', 'New Jersey'),
    ('NM', 'New Mexico'),
    ('NY', 'New York'),
    ('NC', 'North Carolina'),
    ('ND', 'North Dakota'),
    ('OH', 'Ohio'),
    ('OK', 'Oklahoma'),
    ('OR', 'Oregon'),
    ('PA', 'Pennsylvania'),
    ('RI', 'Rhode Island'),
    ('SC', 'South Carolina'),
    ('SD', 'South Dakota'),
    ('TN', 'Tennessee'),
    ('TX', 'Texas'),
    ('UT', 'Utah'),
    ('VT', 'Vermont'),
    ('VA', 'Virginia'),
    ('WA', 'Washington'),
    ('WV', 'West Virginia'),
    ('WI', 'Wisconsin'),
    ('WY', 'Wyoming'),
]
# Create your models here.


class Address(models.Model):
    id = models.AutoField(primary_key=True)
    address1 = models.CharField(max_length=100)
    address2 = models.CharField(max_length=100, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=2, choices=STATES)
    zip = models.PositiveIntegerField()

    def __str__(self):
        if not self.address2:
            return self.address1 + ", " + self.city + ", " + self.state + " " + str(self.zip)
        else:
            return self.address1 + ", " + self.address2 + ", " + self.city + ", " + self.state + " " + str(self.zip)


class UserInfo(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=50)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)


class Quote(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    gallons = models.IntegerField()
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    date = models.DateField()
    price = models.DecimalField(decimal_places=2, max_digits=5)
    total = models.DecimalField(decimal_places=2, max_digits=20)

FuelEst/fuelest/forms.py
from django.forms import ModelForm, Select, DateInput, TextInput
from fuelest.models import UserInfo, Address, Quote
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


class ProfileForm(ModelForm):
    class Meta:
        model = UserInfo
        fields = ['name']
        labels = {
            'name': _('Full Name'),
        }


class AddressForm(ModelForm):
    class Meta:
        model = Address
        fields = ['address1', 'address2', 'city', 'state', 'zip']
        labels = {
            'address1': _('Address Line 1'),
            'address2': _('Address Line 2'),
            'city': _('City'),
            'state': _('State'),
            'zip': _('ZIP Code'),
        }

    def clean(self):
        cleaned_data = super(AddressForm, self).clean()
        zip = cleaned_data.get('zip')
        if len(str(zip)) not in [5, 9]:
            self.add_error(None, ValidationError(
                "ZIP must either be 5 digits or 9"))
            print("Error" + str(len(str(zip))))
        return cleaned_data


class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ['gallons', 'date']
        labels = {
            'gallons': _('Gallons requested'),
            'date': _('Date of delivery'),
        }
        widgets = {
            'date': DateInput(attrs={'class': 'datepicker'}),
        }

FuelEst/fuelest/views.py
from datetime import date
from .models import UserInfo, Address, Quote
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django import forms
from django.utils import timezone
from django.contrib import messages
from fuelest.forms import ProfileForm, AddressForm, QuoteForm
from django.contrib.auth.forms import UserCreationForm
from backports.datetime_fromisoformat import MonkeyPatch
MonkeyPatch.patch_fromisoformat()


class HomePageView(TemplateView):
    template_name = 'fuelest/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        userprof = UserInfo.objects.filter(
            username=User.objects.get(username=self.request.user.username))
        profile_made = (len(userprof) != 0)
        context['profile_made'] = profile_made
        return context


class ProfileView(TemplateView):
    template_name = 'fuelest/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        curuser = ""
        if self.request.user.is_authenticated:
            curuser = self.request.user.username
        userprof = UserInfo.objects.filter(
            username=User.objects.get(username=curuser))
        profile_made = True
        if len(userprof) == 0:
            profile_made = False
        context['profile_made'] = profile_made
        if profile_made:
            userprof = UserInfo.objects.get(
                username=User.objects.get(username=curuser))
            print(userprof)
            context['fullname'] = userprof.name
            useraddr = Address.objects.get(id=userprof.address.id)
            context['addr1'] = useraddr.address1
            context['addr2'] = useraddr.address2
            context['city'] = useraddr.city
            context['state'] = useraddr.state
            context['zip'] = useraddr.zip
        return context


class SuccessView(TemplateView):
    template_name = 'fuelest/quotesuccess.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        userprof = UserInfo.objects.filter(
            username=User.objects.get(username=self.request.user.username))
        profile_made = (len(userprof) != 0)
        context['profile_made'] = profile_made
        return context


class QuoteListView(ListView):
    template_name = "fuelest/quotehist.html"
    paginate_by = 20
    model = Quote

    def get_queryset(self):
        return Quote.objects.filter(
            user=User.objects.get(username=self.request.user.username),
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        userprof = UserInfo.objects.filter(
            username=User.objects.get(username=self.request.user.username))
        profile_made = (len(userprof) != 0)
        context['profile_made'] = profile_made
        addr = Address.objects.get(id=UserInfo.objects.get(
            username=User.objects.get(username=self.request.user.username)).address.id)
        context['addr'] = addr
        return context


def profile_model(request):
    if request.method == "POST":
        profform = ProfileForm(request.POST)
        profile_valid = profform.is_valid()
        addrform = AddressForm(request.POST)
        addr_valid = addrform.is_valid()
        if addr_valid and profile_valid:
            if len(UserInfo.objects.filter(username=User.objects.get(username=request.user.username))) != 0:
                b = UserInfo.objects.get(username=User.objects.get(
                    username=request.user.username))
                b.name = profform['name'].value()
                a = Address.objects.get(id=b.address.id)
                a.address1 = addrform['address1'].value()
                a.address2 = addrform['address2'].value()
                a.city = addrform['city'].value()
                a.state = addrform['state'].value()
                a.zip = addrform['zip'].value()
                a.save()
            else:
                a = addrform.save()
                b = profform.save(commit=False)
            b.username = User.objects.get(username=request.user.username)
            b.address = a
            b.save()
            return redirect("profile")
    else:
        profform = ProfileForm()
        addrform = AddressForm()
    return render(request, "fuelest/editprofile.html", {'profform': profform, 'addrform': addrform})


def register_model(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        form_valid = form.is_valid()
        if form_valid:
            a = form.save()
            return redirect("/")
    else:
        form = UserCreationForm()
    return render(request, "fuelest/register.html", {'form': form})


def calculate_price():
    price = 2.0
    return price


def quote_model(request):
    addr = Address.objects.get(id=UserInfo.objects.get(
        username=User.objects.get(username=request.user.username)).address.id)
    pr = calculate_price()
    userprof = UserInfo.objects.filter(
        username=User.objects.get(username=request.user.username))
    profile_made = (len(userprof) != 0)
    gal_err = ''
    date_err = ''
    pr_err = ''
    tot_err = ''
    gals = None
    del_date = None
    if request.method == "POST":
        gals = request.POST.get('gallons')
        del_date = request.POST.get('delivery_date')
        form_valid = True
        if gals in ['', None] or int(gals) <= 0:
            form_valid = False
            gal_err = "Please enter a positive integer."
        date_s = del_date
        if date_s == '':
            form_valid = False
            date_err = "Please enter a valid future date."
        else:
            try:
                dateT = date.fromisoformat(date_s)
                if dateT < date.today():
                    form_valid = False
                    date_err = "Please enter a valid future date."
            except ValueError:
                form_valid = False
                date_err = "Please enter a valid future date."
        if request.POST.get('pr') == '--':
            form_valid = False
            pr_err = "Please generate price before continuing."
        if request.POST.get('tot') == '--':
            form_valid = False
            tot_err = "Please generate price before continuing."
        if form_valid:
            a = Quote(user=User.objects.get(username=request.user.username))
            a.gallons = gals
            a.address = addr
            a.date = del_date
            a.price = request.POST.get('pr')
            a.total = request.POST.get('tot')
            a.save()
            return redirect("quotesuccess")
    return render(request, "fuelest/fuelquote.html", {"addr": addr, "pr": pr, "profile_made": profile_made, "gal_err": gal_err, "date_err": date_err,
                                                      "pr_err": pr_err, "tot_err": tot_err, "gals": gals, "del_date": del_date,
                                                      "state": addr.state, "hist": (len(Quote.objects.filter(user=User.objects.get(username=request.user.username))) > 0)})

FuelEst/fuelest/templates/fuelest/base.html
<html>

<head>
  {% load static %}
  {% load tags %}
  <link rel="stylesheet" type="text/css" href="{% static 'fuelest/main.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <title>Fuel Appraisal</title>

  {% block headspace %}
  {% endblock %}
</head>

<body>
  <h1 class="title">
    <p
      style="font-family:georgia,garamond,serif;font-size:50px;font-style:italic;color: white;padding-left: 75px;padding-top: 10px;">
      Fuel Appraisal
    </p>
  </h1>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <ul class="nav nav-pills" style="padding-left: 70px">
          <li class="nav-item"><a class="nav-link" href="/index">Home</a></li>
          <li class="nav-item"><a class="nav-link" href="/ ">Logout</a></li>
          {% if profile_made %}
          <li class="nav-item"><a class="nav-link" href="/profile">View/Edit Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="/quotes/generate">Get Fuel Quote</a></li>
          <li class="nav-item"><a class="nav-link" href="/quotes/history">View Quote History</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="/profile/edit">Create Your Profile!</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <span class="content">
    {% block content %}
    {% endblock %}
  </span>
</body>

</html>

FuelEst/fuelest/templates/fuelest/editprofile.html
{% extends "fuelest/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="post" style="color: white;">
    <h1 style="color: white; font-size: 35px;"> Edit Your Profile!</h1>
    {% if form.errors %}
    {% for field in form %}
    {% for error in field.errors %}
    <div>
        {{ error|escape }}
    </div>
    {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
    <div>
        {{ error|escape }}
    </div>
    {% endfor %}
    {% endif %}
    {% csrf_token %}
    {{profform|crispy}}
    {{addrform|crispy}}

    <button type="submit" class="btn btn-default" style="position: relative; bottom: -10px;">Submit</button>
    {% endblock %}

FuelEst/fuelest/templates/fuelest/fuelquote.html
{% extends "fuelest/base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css" />
<script>
  $(function () {
    $(".datepicker").datepicker({
      changeMonth: true,
      changeYear: true,
    });
    $("#id_gallons").change(function () {

      document.getElementById("total_field").value = (Math.ceil({{ pr }} * $("#id_gallons").val() * 100) / 100).toFixed(2);
    });
  $("#get_price").click(function () {
    let price = 0.0;
    let is_valid = true;
    if (document.getElementById("gallons").value <= 0) {
      $('#gal_err_lab').text("Please enter a positive integer.");
      is_valid = false;
    }
    else {
      $('#gal_err_lab').text("");
    }
    if (document.getElementById("delivery_date").value == '') {
      $('#date_err_lab').text("Please enter a valid future date.");
      is_valid = false;
    }
    else {
      date1 = new Date(document.getElementById("delivery_date").value);
      date2 = new Date();
      if (date1 < date2) {
        $('#date_err_lab').text("Please enter a valid future date.");
        is_valid = false;
      }
      else {
        $('#date_err_lab').text("");
      }
    }
    if (is_valid) {
      let base_price = 1.50
      let location_factor = 0.04;
      if ('{{state}}' == 'TX')
        location_factor = 0.02;
      let hist_factor = 0;
      if ('{{hist}}' == 'True')
        hist_factor = 0.01;
      let gal_factor = 0.03;
      if (document.getElementById("gallons").value > 1000)
        gal_factor = 0.02;
      let fluc_factor = 0.04;
      let ddate = new Date(document.getElementById("delivery_date").value);
      if (ddate.getMonth() < 2 || ddate.getMonth() > 7)
        fluc_factor = 0.03;
      margin = base_price * (location_factor - hist_factor + gal_factor + .1 + fluc_factor);
      price = base_price + margin;
      document.getElementById("pr").value = price;
      document.getElementById("total_field").value = price * document.getElementById("gallons").value;
    }
  });
  });
</script>
<form method="post">
  {% if form.errors %}
  {% for field in form %}
  {% for error in field.errors %}
  <div>
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
  <div>
    {{ error|escape }}
  </div>
  {% endfor %}
  {% endif %}
  {% csrf_token %}
  <h1 style="color: white;">Generate a Quote</h1>
  <p style="color: white;">Gallons Requested: <input type="number" id="gallons" name="gallons" value="{{gals}}"><label
      id="gal_err_lab">{{gal_err|crispy}}</label></p>
  <p style="color: white;">Date Of Delivery: <input type="date" id="delivery_date" name="delivery_date"
      value="{{del_date}}"><label id="date_err_lab">{{date_err|crispy}}</label></p>
  <p style="color: white;">Address: <input type="text" name="addr" value="{{addr}}" style="width: 300px;" readonly></p>
  <p style="color: white;">Price: <input type="text" id="pr" value="--" name="pr" readonly><label
      id="pr_err_lab">{{pr_err|crispy}}</label></p>
  <p style="color: white;">Total: <input id="total_field" type="text" name="tot" value="--" readonly><label
      id="tot_err_lab">{{tot_err|crispy}}</label></p>
  <p><button type="button" class="btn btn-default" id="get_price">Get Price</button>
    <button type="submit" class="btn btn-default">Submit</button></p>
</form>
{% endblock %}

FuelEst/fuelest/templates/fuelest/index.html
{% extends "fuelest/base.html" %}

{% block content %}
<p style="font-family:georgia,garamond,serif;font-size:20px;
font-style:italic;color: white; ">Welcome, {{ user.username }}!
</p>
{% if profile_made %}
<p style="color: white; ">Use the tabs above to navigate this website. </p>
{% else %}
<p style="color: white; ">Please click the 'Create Your Profile!' tab above to
    create a profile and access the quotes module.</p>
{% endif %}

{% endblock %}

FuelEst/fuelest/templates/fuelest/login.html
{% load static %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'fuelest/main.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
  {% block content %}
  <p style="font-family:georgia,garamond,serif;font-size:50px;font-style:italic;color:
     white;padding-left: 105px;padding-top: 10px;"> Fuel Appraisal
  </p>
  <div class="content">
    <h1 class="title">
      <p style="font-size:30px;color: white;">
        Login to Fuel Appraisal
      </p>
    </h1>
    <form method="post" style="color: white;">
      {% csrf_token %}
      {{ form.as_p }}
      <button style="position: relative; left: 74px;" type="submit" class="btn btn-light">Login</button>
    </form>
    <a a href="register" style="position: relative; bottom: 53px; left: 200px" class="btn btn-light"
      role="button">Register</a>
    {% endblock %}
  </div>
</body>

FuelEst/fuelest/templates/fuelest/profile.html
{% extends "fuelest/base.html" %}

{% block content %}
{% if profile_made %}
<h1 style="color: white; font-size: 35px;">Your Profile!</h1>
<p style="color: white;">Full name: {{fullname}}</p>
<p style="color: white;">Address 1: {{addr1}}</p>
{% if addr2 %}
<p style="color: white;">Address 2: {{addr2}}</p>
{% endif %}
<p style="color: white;">City: {{city}}</p>
<p style="color: white;">State: {{state}}</p>
<p style="color: white;">Zip: {{zip}}</p>

<a href="edit" class="btn btn-light" role="button">Edit your profile</a>

{% else %}
<p>Please <a href="edit" class='btn btn-default' role='button'>create a profile!</a></p>
{% endif %}
{% endblock %}

FuelEst/fuelest/templates/fuelest/quotehist.html
{% extends "fuelest/base.html" %}

{% block content %}
<h1 style="color: white;"> Fuel Quote History</h1>
<table class="table" style="color: white;">
  <thead>
    <tr>
      <th scope="col" style="color: white;">#</th>
      <th scope="col" style="color: white;">Gallons Requested</th>
      <th scope="col" style="color: white;">Address</th>
      <th scope="col" style="color: white;">Date</th>
      <th scope="col" style="color: white;">Price</th>
      <th scope="col" style="color: white;">Total</th>
    </tr>
  </thead>
  <tbody>
    {% for quote in object_list %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td style="color: white;">{{ quote.gallons }}</td>
      <td style="color: white;">{{ addr }}</td>
      <td style="color: white;">{{ quote.date }}</td>
      <td style="color: white;">{{ quote.price }}</td>
      <td style="color: white;">{{ quote.total }}</td>
    </tr>
    {% empty %}
    <tr>
      <td></td>
      <th scope="row" style="color: white;">No availabe quotes!</th>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

FuelEst/fuelest/templates/fuelest/quotesuccess.html
{% extends "fuelest/base.html" %}
{% block content %}
<p style="color: white;">Success! Quote submitted.</p>
{% endblock %}

FuelEst/fuelest/templates/fuelest/register.html
{% load static %}
{% load crispy_forms_tags %}

<head>
  <link rel="stylesheet" type="text/css" href="{% static 'fuelest/main.css' %}">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
</head>

<body>
  <h1 class="title">
    <p style="font-family:georgia,garamond,serif;font-size:50px;font-style:italic;color:
       white;padding-left: 75px;padding-top: 10px;"> Register A New Account
    </p>
  </h1>
  {% block content %}
  <div class="content" style="color: white;">
    <form method="POST">
      {% csrf_token %}
      {{form|crispy}}

      <button type="submit" class="btn btn-default">Submit</button><br />
    </form>
    <a a href="/" style="position: relative; bottom: 53px; left: 200px" class="btn btn-light" role="button">Back To
      Login</a>
  </div>
  {% endblock %}
</body>